trigger:
  - '*'

# variables:
#   LT_USERNAME: $(UNAME)
#   LT_ACCESS_KEY: $(AKEY)

jobs:
- job: SmartUI_Tests
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  # - task: UseNode@2
  #   inputs:
  #     version: '16.x'

  - script: |
      echo "Installing dependencies"
      npm install @lambdatest/smartui-cli
    displayName: 'Install Dependencies'

  - script: |
      echo "Running SmartUI tests"
      export LT_USERNAME=$(UNAME)
      export LT_ACCESS_KEY=$(AKEY)
      export PROJECT_TOKEN=$(PTOKEN)
      npx smartui --version
      npx smartui exec node index.js --config smartui.json
    displayName: 'Execute SmartUI Tests'